language: python
sudo: false
python:
    - 2.7
    - pypy
    - 3.4
    - 3.5
    - 3.6
matrix:
    include:
        - python: "3.7"
          dist: xenial
          sudo: true
install:
    - pip install zc.buildout
    - buildout
script:
    - bin/test -v1
notifications:
    email: false
