language: python
python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
    - 3.8
    - pypy
    - pypy3
install:
    - virtualenv .
    - bin/pip install zc.buildout
    - bin/buildout
script:
    - bin/test -v1
notifications:
    email: false
